// <auto-generated />
namespace SelectionEquipe_Dev.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SecondModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecondModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202212051119139_SecondModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
